title: Jake Gaylor
description: Engineer and Leader with 15+ years of experience
url: "https://jakegaylor.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Blog settings
show_excerpts: true
future: false

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md 